Refactoring and cleaning up deploy script

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -1,21 +1,57 @@
 #!/usr/bin/env bash
 
-case $1 in
-  staging)
-    destination="s3://staging.zetawar.com"
-    ;;
-  production)
-    destination="s3://www.zetawar.com"
-    ;;
-  *)
-    echo -e "Unknown environment $e"
-    exit 1
-    ;;
-esac
+progname=$(basename $0)
 
-s3cmd sync --exclude '*' --include '*.css' --acl-public -m 'text/css' --add-header='Content-Encoding: gzip' target/ $destination
-s3cmd sync --exclude '*' --include '*.js'  --acl-public -m 'application/javascript' --add-header='Content-Encoding: gzip' target/ $destination
-s3cmd sync --exclude '*' --include '*.html' --acl-public -m 'text/html' --add-header='Content-Encoding: gzip' target/ $destination
-s3cmd sync --exclude '*' --include '*.png' --include '*.jpg' --include '*.ico' --include '*.gif' --acl-public --add-header='Cache-Control: max-age=86400' target/ $destination
-s3cmd sync --exclude '*' --include '*.svg' --acl-public -m 'image/svg+xml' --add-header='Cache-Control: max-age=86400' target/ $destination
-s3cmd sync --delete-removed --acl-public target/ $destination
+function usage {
+  echo "usage: $progname -b BUCKET [-p PREFIX] [-P]"
+  echo "	-b BUCKET	S3 bucket to deploy to"
+  echo "	-p PREFIX	prefix within bucket"
+  echo "	-P		make files public on S3"
+}
+
+while getopts ":b:p:P" opt; do
+  case $opt in
+    b)
+      bucket="$OPTARG"
+      ;;
+    p)
+      prefix="$OPTARG"
+      ;;
+    P)
+      public_opt=--acl-public
+      ;;
+    \?)
+      usage
+      echo "error: invalid option: -$OPTARG" >&2
+      exit 1
+      ;;
+    :)
+      usage
+      echo "error: option -$OPTARG requires an argument" >&2
+      exit 1
+      ;;
+  esac
+done
+
+if [[ ! $bucket ]]; then
+  usage
+  echo "error: you must specify an S3 bucket"
+  exit 1
+fi
+
+destination="s3://$bucket"
+
+if [[ $prefix ]]; then
+  destination="$destination/$prefix"
+fi
+
+gzip_opt="--add-header=Content-Encoding: gzip"
+cache_opt="--add-header=Cache-Control: max-age=86400"
+img_include_opts="--include '*.png' --include '*.jpg' --include '*.ico' --include '*.gif'"
+
+s3cmd sync --exclude '*'         --include '*.css'  -m 'text/css'               $public_opt "$gzip_opt"  target/ $destination
+s3cmd sync --exclude '*'         --include '*.js'   -m 'application/javascript' $public_opt "$gzip_opt"  target/ $destination
+s3cmd sync --exclude '*'         --include '*.html' -m 'text/html'              $public_opt "$gzip_opt"  target/ $destination
+s3cmd sync --exclude '*'         $img_include_opts                              $public_opt "$cache_opt" target/ $destination
+s3cmd sync --exclude '*'         --include '*.svg'  -m 'image/svg+xml'          $public_opt "$cache_opt" target/ $destination
+s3cmd sync --exclude '.htaccess' --delete-removed                               $public_opt              target/ $destination
